### ISSUE TITLE
How are the parallel batons supposed to run?

### ISSUE THREAD

**Issue by huitema** [afrind/draft-frindell-webtrans-devious-baton#2]
The draft says that servers should handle the parameter:

* _count - an integer specifying how many batons will be sent in parallel_

And specify that _"The default value is 1. If the client asks for more batons than the server is capable of sending, the server MUST reject the WebTransport session with a 4xx status code."_

OK, but the devious baton draft supposes that each end does some checks, such as verify that the baton was correctly increased by the peer. If several batons are sent in parallel, these comparisons require a tiny bit of context. My simple proposal is to have the node maintain N baton contexts in parallel. On incoming baton, they find the first available context for which the baton matches the expected value, and run with that. If no context matches, then they detect an error.

Then there is the question of whether all parallel batons should be identical. The draft specifies the parameter:

_* baton - an integer between 0 and 255, inclusive, which the server will use as the initial baton value_

That's kind of a clue: only one baton value, same for all parallel versions. But is that what we expect? 

And then there is the question of termination. Exit if zeroed baton is a fine rule, but is it expected to terminate all parallel runs?

In any case, I would love to see a "parallel batons" section.

**Comment by afrind** [comment]
Great feedback. I'll add a section.

I hadn't thought about verifying the peer had increased the baton correctly and was assuming the peer would always play fair.  Sounds like I ought to add text about handling unexpected baton messages too.

If the `baton` param isn't supplied, and `count` is > 1, I was thinking the server would pick `count` different baton values, and the first one to reach 0 would terminate the session.  If `baton` is supplied, then all sessions could have the same value.  I don't know if the complexity to specify multiple starting baton values from the client is warranted, but maybe it is.

Maybe just send the `baton` param more than once? If `count` is greater than `count(baton)`, server picks random values for the unspecified ones.  If `count` is smaller, then 400?

**Comment by huitema** [comment]
I would like some behavior that I can program and verify in tests. "Same baton" is good enough, and specifying the baton removes the randomness in test results. Not specifying the baton allows for different random values in each parallel run, which is OK if you want random tests. Of course, I could also just fix the random seed in the tests, which makes the behavior somewhat predictable.

There is some remaining randomness in the "first to zero" behavior, even with a single baton value, because one baton run may very well run ahead of the others -- by chance or by flow control. That means I could not do tests such as "how many batons did I see" or "how many bytes did the client receive". The only way I could avoid that is by mandating something like "do no send 0 on any stream unless it can be sent by all streams".

But you have time to decide something. Before that, I need to improve my minimal H3 implementation to accept URL query parameters...
